name: Cleanup Old Cache
on:
  workflow_run:
    workflows: ["Cache Yarn", "Lockfile Maintenance", "Lockfile Maintenance (Client)"]
    branches: [main]
    types: [completed]
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  cleanup-yarn:
    name: Cleanup Yarn
    uses: KenTandrian/workflows/.github/workflows/cleanup.yml@main
    with:
      name: Yarn
      pattern: node-cache-Linux-yarn-
