name: Lockfile Maintenance
on: workflow_dispatch

jobs:
  run:
    name: Run workflow
    uses: KenTandrian/workflows/.github/workflows/lockfile.yml@main
    permissions:
      contents: write
    with:
      package-manager: yarn
      base-version: 1
    secrets: inherit

  client:
    name: Run workflow
    needs: run
    uses: KenTandrian/workflows/.github/workflows/lockfile.yml@main
    permissions:
      contents: write
    with:
      package-manager: yarn
      working-directory: ./client
    secrets: inherit